EOS-18921 : Added srv/config/ documentation and test cases in R2.md
Seagate/cortx-prvsnr pull request #1059
Opened 2021-03-31 09:30 UTC by tanujashinde0405

Added Documenatation for srv/config/ folder in architecture-overview.md and also added test cases for EOS-18921 in r2.md

Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>

-----
[View rendered docs/Architecture/Architectural-Overview.md](https://github.com/Seagate/cortx-prvsnr/blob/EOS-18921-Ducumentation_and_tests/docs/Architecture/Architectural-Overview.md)
[View rendered test/r2.md](https://github.com/Seagate/cortx-prvsnr/blob/EOS-18921-Ducumentation_and_tests/test/r2.md)

2021-03-31 10:21 UTC, ypise requested changes

2021-03-31 10:21 UTC, ypise commented on docs/Architecture/Architectural-Overview.md
> +The config folder structure will look like this:
A representative config directory structure shall be:

2021-03-31 10:21 UTC, ypise commented on docs/Architecture/Architectural-Overview.md
> +each file would consist of:
A new line starts in Caps. Do maintain the basic grammar discipline.

`each file would consist of:` => `Each sub-level file would consist of calls to respective southbound API as:  `

2021-03-31 10:21 UTC, ypise commented on test/r2.md
> +Step 2: Run deploy_vm command to deploy system and prereq states
EOS-18921 applies for cortx components.
Thus, only the following are desired:
```
		provisioner deploy_vm --setup-type single --states iopath
		provisioner deploy_vm --setup-type single --states controlpath
		provisioner deploy_vm --setup-type single --states ha 
```

2021-04-01 04:26 UTC, tanujashinde0405 commented
Addressed codacy issues and documentation changes

2021-04-01 06:55 UTC, ypise approved these changes

2021-04-26 16:23 UTC, ypise approved these changes

2021-04-26 17:39 UTC, merged