EOS-18920: Patch-1: create separate validation modules and remove from configure_setup api
Seagate/cortx-prvsnr pull request #1060
Opened 2021-03-31 11:45 UTC by divya-vijay

Signed-off-by: Divya Vijayakumar <divya.vijaykumar@seagate.com>

2021-03-31 13:08 UTC, ypise approved these changes

2021-04-01 10:04 UTC, andkononykhin2 requested changes
@divya-vijay Thanks. Could you please just address few comments?

2021-04-01 10:04 UTC, andkononykhin2 commented on api/python/provisioner/commands/validator/__init__.py
> -                        YumRepoDataValidator,
why it was removed?

2021-04-01 10:13 UTC, divya-vijay commented on api/python/provisioner/commands/validator/network.py
> +from ...inputs import (
yes, thought so :) But in existing `commands/validators/validator.py`, it was this way. so, kept it as such to maintain uniformity. Addressed now.

2021-04-01 10:13 UTC, divya-vijay commented on api/python/provisioner/commands/validator/__init__.py
> -                        YumRepoDataValidator,
Duplicated twice, so removed once.

2021-04-01 10:39 UTC, andkononykhin2 commented on api/python/provisioner/commands/validator/__init__.py
> -                        YumRepoDataValidator,
Oh, right. Thanks

2021-04-01 10:41 UTC, andkononykhin2 commented on api/python/provisioner/commands/validator/network.py
> +from ...inputs import (
I see. We missed that before. Thank you for the update.

2021-04-01 10:41 UTC, andkononykhin2 approved these changes

2021-04-05 12:20 UTC, merged