Move enclosure-id to mine data
Seagate/cortx-prvsnr pull request #1087
Opened 2021-04-07 09:34 UTC by sradhanand-pati

Signed-off-by: sradhanandpati <sradhanand.pati@seagate.com>

2021-04-07 11:08 UTC, 83bhp approved these changes
Looks good, please address the typo in storage_sls.template file for node_num variable.

2021-04-07 16:18 UTC, ypise requested changes
Reconsider the changes

2021-04-07 16:18 UTC, ypise commented on srv/components/system/storage/enclosure_id/config/sync.sls
> +Sync grains data and mine data for enclosure_id:
Why do we need separate sync.sls after set.sls?
Also, config.set could be part of config.sls

2021-04-09 09:27 UTC, ypise approved these changes

2021-04-09 10:58 UTC, mazinamdar approved these changes

2021-04-09 11:47 UTC, merged