EOS-19760: fix for OVA bootstrap script issue
Seagate/cortx-prvsnr pull request #1184
Opened 2021-04-28 16:06 UTC by rahuljyoti65

Signed-off-by: Rahul Jyoti <rahul.jyoti@seagate.com>
Bootstrap script execution was not proceeding further and was stuck at "Configuring haproxy and s3" stage. This was because kafka was not running.
Fix:
1. starting kafka before configuring s3server.
2. increased the delay to 30s after starting zookeeper. ( bcoz on executing kafta.start using salt only zookeeper was starting and not kafka)

2021-04-28 18:27 UTC, ypise requested changes

2021-04-28 18:27 UTC, ypise commented on cli/src/virtual_appliance/bootstrap.sh
> +salt-call state.apply components.hare.config.prepare
This should not be necessary on R2.
Check with hare team, which interface they define configures the CDF file.

2021-04-28 18:27 UTC, ypise commented on srv/components/misc_pkgs/kafka/start.sls
>  Wait for zookeeper to start:
The sanity_check takes care of this, thus this wait should be removed.

2021-04-29 13:16 UTC, rahuljyoti65 commented
Clsoing this PR as the issue is addressed in another PR https://github.com/Seagate/cortx-prvsnr/pull/1190

2021-04-29 13:16 UTC, closed without merging