EOS-19888: Setup Consul - Basic service
Seagate/cortx-prvsnr pull request #1229
Opened 2021-05-10 13:14 UTC by tanujashinde0405

2021-05-10 14:16 UTC, ypise requested changes

2021-05-10 14:16 UTC, ypise commented on srv/components/misc_pkgs/consul/files/consul_server.json.j2
> +
This extra empty line is unnecessary at the end of file.

2021-05-10 14:16 UTC, ypise commented on srv/components/misc_pkgs/consul/teardown.sls
> +     - name: consul
Is this not automatically effected by rpm uninstall?

2021-05-10 14:16 UTC, ypise commented on pillar/components/firewall.sls
> +      consul:
Consul is supposed to run on private data interface. Comment these entries for now.

2021-05-10 14:16 UTC, ypise commented on api/python/provisioner/srv/salt/firewall/config.sls
> +      - 8301/tcp
Consul is supposed to run on private data interface. Comment this entry for now.

2021-07-21 06:25 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-10-05 17:16 UTC, closed without merging