EOS-21409: removed enable from kibana and csm as pcs enables services
Seagate/cortx-prvsnr pull request #1470
Opened 2021-07-05 13:16 UTC by tanujashinde0405

Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>

2021-07-05 14:05 UTC, mazinamdar approved these changes

2021-07-05 14:34 UTC, 83bhp approved these changes

2021-07-06 05:15 UTC, nitin-seagate approved these changes
LGTM

2021-07-06 05:15 UTC, nitin-seagate requested changes

2021-07-06 05:15 UTC, nitin-seagate commented on srv/components/misc_pkgs/kibana/start.sls
> +    - enabled: True
Please check this one

2021-07-06 05:18 UTC, nitin-seagate approved these changes
LGTM

2021-07-06 05:25 UTC, 83bhp commented on srv/components/misc_pkgs/kibana/start.sls
> +    - enabled: True
enable is correct..

2021-07-06 05:29 UTC, merged