fix network configuration issues with mtu and prefix
Seagate/cortx-prvsnr pull request #1473
Opened 2021-07-05 13:57 UTC by SomwanshiAnjali

Fixed below network configurations:
1. Add `mtu` parameter to `cortx_setup node prepare network` command
2. Remove statically added prefix value from srv/components/system/network/data/direct.sls
3. Use `netmask` and `gateway` for private_data network.

Signed-off-by: Anjali Somwanshi <anjali.somwanshi@seagate.com>

2021-07-05 14:33 UTC, 83bhp approved these changes
Looks good, as discussed remove the mtu parameter as of now, let's discuss it with Nitin and add it later on.

2021-07-05 14:58 UTC, sradhanand-pati approved these changes

2021-07-06 04:41 UTC, mazinamdar approved these changes
looks good to me

2021-07-06 04:53 UTC, nitin-seagate approved these changes
Looks good to me...
Where do we post changes for default MTU=9000 (Hardware)

2021-07-06 04:57 UTC, nitin-seagate requested changes

2021-07-06 04:57 UTC, nitin-seagate commented on api/python/provisioner/inputs.py
>          default=1500
The default value of MTU for hardware should be `9000`, else it should be `1500`

2021-07-06 05:35 UTC, nitin-seagate requested changes

2021-07-06 05:35 UTC, nitin-seagate commented on lr-cli/cortx_setup/commands/node/prepare/network.py
> +            mtu = '9000' if server_type == 'physical' else '1500'
mtu = '1500' if server_type == 'virtual' or network_type == 'management' else '9000'

2021-07-06 05:48 UTC, nitin-seagate approved these changes
LGTM

2021-07-06 06:09 UTC, merged