EOS-21906
Seagate/cortx-prvsnr pull request #1510
Opened 2021-07-19 11:45 UTC by zahidsk

2021-07-19 12:25 UTC, nitin-seagate requested changes
The change-set is huge? Please confirm

2021-07-19 12:47 UTC, zahidsk commented
> The change-set is huge? Please confirm

I did just few line changes in below 2 files but still git is showing as whole file change, (I cross checked using line no)
cortx_setup/__init__.py
cortx_setup/api_spec.yaml

2021-07-19 13:34 UTC, zahidsk commented
> > The change-set is huge? Please confirm
> 
> I did just few line changes in below 2 files but still git is showing as whole file change, (I cross checked using line no)
> cortx_setup/**init**.py
> cortx_setup/api_spec.yaml

identified and correction commited

2021-07-19 14:41 UTC, nitin-seagate approved these changes
LGTM

2021-07-19 14:42 UTC, nitin-seagate approved these changes

2021-07-19 14:42 UTC, nitin-seagate commented on lr-cli/cortx_setup/commands/config/set.py
> +        Conf.save('node_info_index')
Please add new line..

2021-07-21 06:25 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-07-22 10:18 UTC, nitin-seagate approved these changes
LGTM

2021-07-22 10:21 UTC, sradhanand-pati approved these changes
Looks Good to me.
Please updatethe PR title.

2021-07-22 11:23 UTC, mazinamdar approved these changes
looks good , just make sure to add  Copyright data in lr-cli/cortx_setup/commands/config/__init__.py

2021-07-23 09:13 UTC, closed without merging

2021-07-23 09:14 UTC, 83bhp commented
The changes got landed via PR: https://github.com/Seagate/cortx-prvsnr/pull/5985