EOS-22259 Populate DIX Pool layout parameters to confstore file
Seagate/cortx-prvsnr pull request #5998
Opened 2021-07-26 13:22 UTC by zahidsk

Signed-off-by: zahid.shaikh <zahid.shaikh@seagate.com>

2021-07-26 13:25 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-07-27 05:47 UTC, nitin-seagate requested changes

2021-07-27 05:47 UTC, nitin-seagate commented on lr-cli/cortx_setup/commands/storageset/config/durability.py
> +            ss_name = Conf.get(index,
How will this work for multiple storage sets?
Tomorrow we may have 2-3 storage sets in which case only storage_set[0] will not work

2021-07-27 07:10 UTC, nitin-seagate requested changes
Not sure this changes are correct

2021-07-27 07:10 UTC, nitin-seagate commented on lr-cli/cortx_setup/commands/storageset/config/durability.py
> +            ss_name = Conf.get(index,
Lets leave storage-set for now

2021-07-28 06:59 UTC, nitin-seagate approved these changes
Looks good to me

2021-07-30 07:22 UTC, merged