EOS-22259 bound durability type to sns or dix
Seagate/cortx-prvsnr pull request #6014
Opened 2021-07-30 12:43 UTC by zahidsk

2021-07-30 12:45 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-08-02 04:30 UTC, sradhanand-pati commented on lr-cli/cortx_setup/commands/storageset/config/durability.py
> +            if kwargs['durability_type'] not in ['sns', 'dix']:
add choices in args defined above..
argparser will handle it internally

2021-08-02 06:18 UTC, nitin-seagate requested changes
The code changes does not export latest values to ConfStore (Please fix that issue)

2021-08-02 06:18 UTC, nitin-seagate commented on lr-cli/cortx_setup/commands/storageset/config/durability.py
> +                               f'cluster>{cluster_id}>storage_set[0]>name')
Try to accommodate multiple storage-set as well here...

2021-08-02 07:44 UTC, sradhanand-pati commented
Closing it as it will be addressed in  - https://github.com/Seagate/cortx-prvsnr/pull/6017

2021-08-02 07:44 UTC, closed without merging