EOS-24431: Containerization Support for Storage PVCs
Seagate/cortx-prvsnr pull request #6155
Opened 2021-09-16 07:46 UTC by jjxsg

# Problem Statement
Containerization Support for Storage PVCs

# Design
PV/PVC configuration for various storage requirements. 

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent.

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2021-09-16 07:50 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-09-16 09:03 UTC, ujjwalpl requested changes

2021-09-16 09:03 UTC, ujjwalpl commented on test/volumes/cortx-deployment.yml
> +apiVersion: apps/v1
Please move this code to cortx-prvsnr/experiments folder.

2021-09-16 10:03 UTC, cdeshmukh commented on test/volumes/cortx-pv-shared.yml
> +    path: /data/pv/shared
this path needs to be replaced from config dynamically, before PV/PVC can be deployed

2021-09-16 10:07 UTC, cdeshmukh commented on test/volumes/deploy.sh
> +kubectl apply -f "$SCRIPT_DIR"/cortx-pv-logs.yml --namespace cortx
namespace we can have it as seagate-cortx, as a recommendation ofcourse

2021-09-17 03:32 UTC, jjxsg commented
Closing this PR as PV/PVC infrastructure code is already in place. Finding of the POC will be updated in the confluence page.

2021-09-17 03:32 UTC, closed without merging