Eos 24474 2:  Changed the PV and PVC storage capacity and volume paths
Seagate/cortx-prvsnr pull request #6186
Opened 2021-09-27 13:32 UTC by kailashyadav11

Signed-off-by: Kailash Yadav <kailash.yadav@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2021-09-27 13:35 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-09-28 04:43 UTC, nitin-seagate approved these changes
LGTM

2021-09-28 07:17 UTC, nitin-seagate requested changes

2021-09-28 07:17 UTC, nitin-seagate commented on test/deploy/kubernetes/persistent-volumes/storage_devices_node1.yaml
> +          - node1
Add new line at EOF

2021-09-28 07:17 UTC, nitin-seagate commented on test/deploy/kubernetes/persistent-volumes/storage_devices_node2.yaml
> +          - node2
Add new line at EOF

2021-09-28 07:17 UTC, nitin-seagate commented on test/deploy/kubernetes/volume-claims/storage_volumes_node2.yaml
> +  volumeName: local-node2
Add new line at EOF

2021-09-28 07:17 UTC, nitin-seagate commented on test/deploy/kubernetes/volume-claims/storage_volumes_node3.yaml
> +  volumeName: local-node3
Add new line at EOF

2021-09-28 07:17 UTC, nitin-seagate commented on test/deploy/kubernetes/volume-claims/storage_volumes_node1.yaml
> +  volumeName: local-node1
Add new line at EOF

2021-09-28 07:18 UTC, nitin-seagate approved these changes
LGTM

2021-09-28 07:24 UTC, 83bhp approved these changes

2021-09-28 07:24 UTC, merged