Updated upgrade.sh and readme file for redefined pods
Seagate/cortx-prvsnr pull request #6320
Opened 2022-01-05 14:11 UTC by cahuja123

Signed-off-by: Chirag Ahuja <chirag.ahuja@seagate.com>

# Problem Statement
- Modified upgrade.sh for re-defined Pods

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-01-05 14:41 UTC, tanujashinde0405 requested changes

2022-01-05 14:41 UTC, tanujashinde0405 commented on test/deploy/kubernetes/upgrade.sh
> +done <<< "$(kubectl get pods --namespace=$namespace | grep 'data-node.-*.\|control-node-.*\|server-node.-.*\|ha-node-.*\|storage-node.-.*')"
Pull double quotes for variables-> "$namespace"

2022-01-05 14:41 UTC, tanujashinde0405 commented on test/deploy/kubernetes/upgrade.sh
> +        kubectl set image deployment $SERVER_NODE cortx-setup=$UPGRADE_IMAGE cortx-motr-hax=$UPGRADE_IMAGE cortx-s31=$UPGRADE_IMAGE  cortx-s32=$UPGRADE_IMAGE cortx-s3-auth-server=$UPGRADE_IMAGE  cort
put double quotes on $DATA_NODE , $SERVER_NOD, $STOARGE_NODE, $UPGRADE_IMAGE

2022-01-05 14:50 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-01-06 04:00 UTC, tanujashinde0405 approved these changes
LGTM, Please make the upgrade executable.

2022-01-06 04:40 UTC, cahuja123 commented on test/deploy/kubernetes/upgrade.sh
> +        kubectl set image deployment $SERVER_NODE cortx-setup=$UPGRADE_IMAGE cortx-motr-hax=$UPGRADE_IMAGE cortx-s31=$UPGRADE_IMAGE  cortx-s32=$UPGRADE_IMAGE cortx-s3-auth-server=$UPGRADE_IMAGE  cort
Done

2022-01-06 04:41 UTC, cahuja123 commented
> LGTM, Please make the upgrade executable.

Done.

2022-01-06 04:59 UTC, shriya-deshmukh approved these changes

2022-01-06 05:12 UTC, kailashyadav11 approved these changes
LGTM

2022-01-06 05:48 UTC, merged