Update numpy version
Seagate/cortx-prvsnr pull request #6335
Opened 2022-02-21 10:07 UTC by swanand-gadre

Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>

# Problem Statement
- Problem statement

Current python version in all cortx pods is at python 3.6.8. All the versions of numpy above 1.19.X (i.e. 1.20.X, 1.21.X, 1.22.X) are not available for python 3.6.8.
Infact they are available from python 3.7.X ot 3.8.X onwards. So unless python version is not upgraded, numpy cannot be upgraded to the next version.

So plan is to upgrade numpy to latest minor version of 1.19.5. This upgrade will not fix any existing vulnerabilities, but from compliance perspective, it will take numpy to latest minor version compatible with cortx – python version.

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design
https://jts.seagate.com/browse/CORTX-28905

# Coding
   Checklist for Author
-  [X] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [X] Unit and System Tests are added
- [X] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [X] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [X] JIRA number/GitHub Issue added to PR
- [X] PR is self reviewed
- [X] Jira and state/status is updated and JIRA is updated with PR link
- [X] Check if the description is clear and explained

https://jts.seagate.com/browse/CORTX-28905

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

Not Applicable

2022-02-21 10:09 UTC, kailashyadav11 approved these changes
LGTM

2022-02-21 10:10 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-02-23 04:43 UTC, tanujashinde0405 approved these changes

2022-02-23 04:48 UTC, tanujashinde0405 requested changes
Please rebase with main once.

2022-02-24 11:56 UTC, tanujashinde0405 approved these changes

2022-02-24 12:20 UTC, merged