[WIP] CI-CD Pipeline for Provisioner team with Granular images deployment.
Seagate/cortx-prvsnr pull request #6344
Opened 2022-03-15 06:01 UTC by ashukakkar

# Problem Statement
- Pipeline with Granular images deployment.

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-03-15 06:05 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-03-16 05:07 UTC, tanujashinde0405 requested changes

2022-03-16 05:07 UTC, tanujashinde0405 commented on devops/ci/update_solution.sh
> +    pushd $WORKSPACE/devops/ci
add double-quotes to "$WORKSPACE"

2022-03-16 05:07 UTC, tanujashinde0405 commented on devops/ci/update_solution.sh
> +    pushd $WORKSPACE/devops/ci
add double quotes to all variables in this script

2022-03-28 07:46 UTC, ashukakkar commented
As discussed the Jenkins code will go to RE repo. So, closing this PR.
Raised another PR for RE repo: https://github.com/Seagate/cortx-re/pull/935

2022-03-28 07:46 UTC, closed without merging