CORTX-32832: fixing unit tests in test_setup
Seagate/cortx-prvsnr pull request #6407
Opened 2022-08-30 12:05 UTC by lakshita-jain

Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>

# Problem Statement

*   fix the existing Unit Tests in Provisioner

## Design

*   add cortx_setup module in imports
*   For Feature, Post the link for design

## Coding

Checklist for Author

*   \[ ] Coding conventions are followed and code is consistent

## Testing

Checklist for Author

*   \[ ] Unit and System Tests are added
*   \[ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
*   \[ ] Testing was performed with RPM

## Impact Analysis

Checklist for Author/Reviewer/GateKeeper

*   \[ ] Interface change (if any) are documented
*   \[ ] Side effects on other features (deployment/upgrade)
*   \[ ] Dependencies on other component(s)

## Review Checklist

Checklist for Author

*   \[ ] JIRA number/GitHub Issue added to PR
*   \[ ] PR is self reviewed
*   \[ ] Jira and state/status is updated and JIRA is updated with PR link
*   \[ ] Check if the description is clear and explained

## Documentation

Checklist for Author

*   \[ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-08-30 12:13 UTC, tanujashinde0405 requested changes
fix codacy

2022-08-31 09:45 UTC, lakshita-jain commented
> fix codacy
@tanujashinde0405: The codacy cant be fixed as the module is being used in line number 45( sys.modules), removing the package will throw error and the unit tests will fail.

2022-09-06 03:37 UTC, tanujashinde0405 approved these changes

2022-09-06 05:12 UTC, nitin-seagate approved these changes
Fix codacy issue...

2022-09-06 05:15 UTC, merged