Salt log filtering
Seagate/cortx-prvsnr pull request #691
Opened 2020-10-29 12:36 UTC by AshwiniS-Borse

rsyslog handler, file handler: need to configure to filter out salt logs lower than INFO level
one more file handle: need to route all salt logs from DEBUG level and higher there

2020-10-29 16:31 UTC, andkononykhin2 requested changes
@AshwiniS-Borse Very good PR, thank you! It follows the related task's design very closely. But some changes are needed. Please check and address comments.

Also please update the title to refer the task. e.g. [EOS-12345] ... title ...

2020-10-29 16:31 UTC, andkononykhin2 commented on api/python/provisioner/log.py
> +class LogFileFilter(logging.Filter):
please don't combine two filters, python handlers [accept](https://docs.python.org/3.6/library/logging.config.html#dictionary-schema-details) list of filters

2020-10-29 16:31 UTC, andkononykhin2 commented on api/python/provisioner/log.py
> +            return False
I believe you may combined that to simplify:
```
return not ( record.name.startswith("salt.") and (record.levelno < logging.INFO) )
```

2020-10-29 16:31 UTC, andkononykhin2 commented on api/python/provisioner/log.py
> +        if record.name.startswith("salt."):
that might be simplified as well

2020-10-29 16:31 UTC, andkononykhin2 commented on api/python/provisioner/log.py
> +        elif ( hname == logfile_handler ) or ( hname == saltlogfile_handler ):
possible other way of the same
```
hname in (logfile_handler, saltlogfile_handler)
```

2020-10-29 16:31 UTC, andkononykhin2 commented on api/python/provisioner/log.py
> +                            'help': f"{saltlogfile_handler} handler file path",
you need to support both log files, not only salt's one

2020-10-29 16:31 UTC, andkononykhin2 commented on api/python/provisioner/log.py
> +                                f"{saltlogfile_handler} handler "
the same as above

2020-10-29 16:31 UTC, andkononykhin2 commented on api/python/provisioner/log.py
> +                                f"{saltlogfile_handler} handler "
the same as above

2020-10-29 16:31 UTC, andkononykhin2 commented on api/python/provisioner/provisioner.conf
> +      filters: [log_filter]
as I mentioned above, please use multiple filters here instead of a super one

2020-10-29 16:31 UTC, andkononykhin2 commented on api/python/provisioner/provisioner.conf
> +
please either add new lines between other blocks or remove that one

2020-11-07 12:16 UTC, andkononykhin2 approved these changes
Thank you. Looks good now. Please ensure flake8 passes though.

2020-11-07 12:16 UTC, andkononykhin2 commented on api/python/provisioner/log.py
> +        return not(record.name.startswith("salt.")
I believe flake8 will complain here

2020-12-04 13:16 UTC, ypise approved these changes

2020-12-07 10:38 UTC, merged