EOS-15766: Design and implement the logic of resume after reboot
Seagate/cortx-prvsnr pull request #827
Opened 2021-01-09 19:42 UTC by SomwanshiAnjali

Signed-off-by: Anjali Somwanshi <anjali.somwanshi@seagate.com>

PR includes below changes for EOS-15766:

1. Create service to resume after reboot in between software update process
2. Create script to run provisioner commands by checking pillar data 
for now, below format considered for pillar:

`
update_states:
  pre_boot:
    - state1
    - state2
  post_boot:
    - state1
    - state2
`
For now, considered these states as provisioner commands

2021-01-11 04:52 UTC, andkononykhin2 approved these changes

2021-01-13 19:02 UTC, ypise approved these changes

2021-01-13 19:02 UTC, ypise commented on cli/src/update-post-reboot.sh
> +#!/bin/bash
@SomwanshiAnjali 
The general instructions for us are to have lesser batch scripts and more Python code.
Is it possible to convert this to Python code?
Also, move this code under dedicated upgrade directory:
`cli/src/upgrade/update-post-reboot.sh`

2021-01-13 19:03 UTC, ypise requested changes

2021-01-13 19:03 UTC, ypise commented on cli/src/update-post-reboot.sh
> +#!/bin/bash
@SomwanshiAnjali
The general instructions for us are to have lesser batch scripts and more Python code.
Is it possible to convert this to Python code?
Also, move this code under dedicated upgrade directory:
`cli/src/upgrade/update-post-reboot.sh`

2021-01-14 13:48 UTC, andkononykhin2 commented on cli/src/update-post-reboot.sh
> +#!/bin/bash
@ypise It's good to move that file to a separate dir as you suggested but I think we can keep bash for now. Actually it was me who asked @SomwanshiAnjali to do just a PoC without any restrictions regarding implementation. I believe python will definitely come into play soon in scope of the next upgrade PR from Anjali.

2021-01-15 08:53 UTC, ypise reviewed
Forgot to update this one.

2021-01-15 14:43 UTC, SomwanshiAnjali commented on cli/src/update-post-reboot.sh
> +#!/bin/bash
Addressed

2021-01-15 14:43 UTC, SomwanshiAnjali commented on cli/src/update-post-reboot.sh
> +    fi
Addressed

2021-01-18 05:57 UTC, ypise approved these changes

2021-01-18 05:58 UTC, ypise approved these changes

2021-01-18 06:16 UTC, merged