EOS-16670: Convert controller-cli bash scripts to python scripts
Seagate/cortx-prvsnr pull request #877
Opened 2021-02-08 05:00 UTC by rahuljyoti65

Signed-off-by: Rahul Jyoti <rahul.jyoti@seagate.com>

2021-02-08 06:44 UTC, 83bhp commented
Had one round of review, looks good, let's try to run it together to test various scenarios.
Also please fix the COdacy reported issues.

2021-02-08 11:00 UTC, ypise requested changes

2021-02-08 11:00 UTC, ypise commented on srv/components/controller/files/python-scripts/xml.py
> +import logging
`srv/components/controller/files/python-scripts/xml.py`
`python-scripts` is not necessary, just call it `scripts`

Also, rename the file to: `srv/components/controller/files/scripts/xml_parser.py`

Do we really need this file? I feel we don't need to have a separate parser module in Python, we can use standard xml parser.

Secondly, we don't need xml as we can capture output as JSON. @83bhp need your help with JSON

2021-02-25 07:50 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-03-05 05:17 UTC, closed without merging