EOS-17486:Remove s3iamcli installation from s3server.install
Seagate/cortx-prvsnr pull request #883
Opened 2021-02-10 10:55 UTC by sradhanand-pati

Signed-off-by: sradhanandpati <sradhanand.pati@seagate.com>

2021-02-10 11:09 UTC, AjinkyaDhumal approved these changes

2021-02-11 06:02 UTC, nitin-seagate approved these changes
Looks good to me...

2021-02-11 06:04 UTC, 83bhp requested changes
Changes look ok, please also remove the s3iamcli from teardown state.

2021-02-11 06:04 UTC, 83bhp commented on srv/components/s3server/install.sls
> +#Install cortx-s3iamcli:
Please delete the lines instead of commenting.

2021-02-11 06:21 UTC, 83bhp approved these changes
Looks good!

2021-02-11 10:00 UTC, amitwac2608 approved these changes

2021-02-11 10:03 UTC, merged

2021-02-11 10:03 UTC, nitin-seagate commented
Merge this changes to main branch